README.md, resources/lang/en.json, resources/lang/pl.json, resources/views/partials/modules/show_recommendations.blade.php
I corrected the instructions for adding translations in readme.md
I divided the text of the recommendation into 3 parts to make it easier.
=> separation texts

resources/lang/en.json, resources/lang/es.json
Adds a missing key to the English localization file
=> [en] Add missing localization key

resources/views/partials/tables/show_table.blade.php, tests/Feature/ShowVersionTest.php
fixed error 500 noticed when we want to see a version where there is no date BUG FIXES UNTIL or SECURITY FIXES UNTIL
e.g. https://laravelversions.com/4.2
=> fix is no dates + tests

app/Http/Controllers/LaravelVersionsController.php
=> fixed #48 - day after support ends

composer.json, composer.lock, config/localized-routes.php, resources/lang/pl.json, routes/web.php, tests/Feature/ExampleTest.php, tests/Feature/LaravelVersionFromPathTest.php
I turned on the auto language setting based on the browser.
If there is no translation of the language, it sets EN.
Now the EN language address is redirected from ```/``` to ```/en```, so when someone enters / ie (http://laravelversions.com/) the browser language is checked or the language already set early and redirects to the appropriate language page of the page.
Thanks to this, when someone returns to the website, they have the language set to the one they previously set. 
:)
=> Auto set locale lang

resources/lang/en.json, resources/lang/pl.json, resources/views/versions/index.blade.php
- I added the ability to translate the sentence "You can also find a list of all of the security advisories for Laravel here:".
- I added a translated sentence in PL
=> Add new sentence translated

resources/lang/de.json, resources/lang/es.json, resources/lang/fr.json, resources/lang/id.json, resources/lang/it.json, resources/lang/ja.json, resources/lang/lt.json, resources/lang/pt_BR.json, resources/lang/ru.json, resources/lang/uk.json, resources/lang/vi.json, resources/lang/zh_CN.json
After the positive merge of PR #65, I add a new sentence to be translated in other translation languages, so that the translation maintainers would be easier to translate without adding it to the file;)
CC (the guardians of languages):
=> Add new sentence in langs

.github/workflows/lint.yml, .github/workflows/run-tests.yml, composer.json, composer.lock
Includes Laravel 8.83 Shift.
**Note: Requires server upgrade action to deploy**
=> PHP 8.0 upgrade

.git-blame-ignore-revs, .github/workflows/run-duster.yml, app/Console/Commands/FetchLatestReleaseNumbers.php, app/Exceptions/Handler.php, app/Http/Controllers/Api/LaravelVersionsController.php, app/Http/Controllers/LaravelVersionsController.php, app/Http/Middleware/RedirectIfAuthenticated.php, composer.json, composer.lock, database/factories/LaravelVersionFactory.php, resources/views/components/language-selector.blade.php, resources/views/partials/modules/show_recommendations.blade.php, resources/views/partials/tables/eol_table.blade.php, resources/views/partials/tables/show_table.blade.php, tests/Feature/ApiShowVersionTest.php, tests/Feature/ExampleTest.php, tests/Unit/ExampleTest.php
>**Warning** This PR builds off #124 and will need to be merged in after.
---
This PR adds and configures Duster.
Duster has been run against the codebase to fix any current issues.
Dusting commit ignored in `git blame`.
=> Add and run Duster

lang/id.json
Added translations on supported PHP versions.
=> Update id_ID translation

composer.json, composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.1.5` branch.
- Checkout the `shift-ci-v10.1.5` branch
=> Laravel 10.1.5 Shift

.gitignore, composer.json, composer.lock, phpunit.xml
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.8.0` branch.
- Checkout the `shift-ci-v10.8.0` branch
=> Laravel 10.8.0 Shift

composer.json, composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.9.0` branch.
- Checkout the `shift-ci-v10.9.0` branch
=> Laravel 10.9.0 Shift

composer.json, composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.11.0` branch.
- Checkout the `shift-ci-v10.11.0` branch
=> Laravel 10.11.0 Shift

composer.json, composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.13.2` branch.
- Checkout the `shift-ci-v10.13.2` branch
=> Laravel 10.13.2 Shift

.github/workflows/run-duster.yml, app/Http/Middleware/RedirectIfAuthenticated.php, bootstrap/app.php, composer.json, composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.15.0` branch.
- Checkout the `shift-ci-v10.15.0` branch
=> Laravel 10.15.0 Shift

app/Console/Commands/FetchLatestReleaseNumbers.php, app/Http/Resources/LaravelVersionResource.php, database/migrations/2023_08_25_202719_add_supported_php_to_laravel_versions_table.php, manual-version-info.json, resources/views/partials/tables/current_table.blade.php, resources/views/partials/tables/eol_table.blade.php, resources/views/partials/tables/show_table.blade.php, resources/views/versions/index.blade.php, tests/Feature/ApiListVersionsTest.php
Closes #20.
Also moves the important dates that we can't pull from the API into a JSON file so it can be committed to code.
=> Add supported PHP versions

composer.json, composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.21.0` branch.
- Checkout the `shift-ci-v10.21.0` branch
=> Laravel 10.21.0 Shift

composer.json, composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.23.1` branch.
- Checkout the `shift-ci-v10.23.1` branch
=> Laravel 10.23.1 Shift

.github/workflows/run-tests.yml, composer.json, composer.lock, package-lock.json
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.40.0` branch.
- Checkout the `shift-ci-v10.40.0` branch
=> Laravel 10.40.0 Shift

composer.json, composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.42.0` branch.
- Checkout the `shift-ci-v10.42.0` branch
=> Laravel 10.42.0 Shift

composer.json, composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.43.0` branch.
- Checkout the `shift-ci-v10.43.0` branch
=> Laravel 10.43.0 Shift

manual-version-info.json
See https://laravel.com/docs/master/releases#support-policy
=> Fix Laravel 9 security fixes end date

composer.json, composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.44.0` branch.
- Checkout the `shift-ci-v10.44.0` branch
=> Laravel 10.44.0 Shift

composer.json, composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.45.1` branch.
- Checkout the `shift-ci-v10.45.1` branch
=> Laravel 10.45.1 Shift

composer.json, composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.46.0` branch.
- Checkout the `shift-ci-v10.46.0` branch
=> Laravel 10.46.0 Shift

composer.json, composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.47.0` branch.
- Checkout the `shift-ci-v10.47.0` branch
=> Laravel 10.47.0 Shift

composer.json, composer.lock, package-lock.json
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.48.3` branch.
- Checkout the `shift-ci-v10.48.3` branch
=> Laravel 10.48.3 Shift

composer.lock, package-lock.json
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.48.4` branch.
- Checkout the `shift-ci-v10.48.4` branch
=> Laravel 10.48.4 Shift

composer.lock, package-lock.json
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.48.5` branch.
- Checkout the `shift-ci-v10.48.5` branch
=> Laravel 10.48.5 Shift

composer.json, composer.lock, package-lock.json
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.48.8` branch.
- Checkout the `shift-ci-v10.48.8` branch
=> Laravel 10.48.8 Shift

composer.lock, package-lock.json
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.48.10` branch.
- Checkout the `shift-ci-v10.48.10` branch
=> Laravel 10.48.10 Shift

composer.lock, package-lock.json
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.48.12` branch.
- Checkout the `shift-ci-v10.48.12` branch
=> Laravel 10.48.12 Shift

composer.json, composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as bumps your package dependencies. You may review the full list of changes in the [Laravel Release Notes](https://github.com/laravel/framework/releases/tag/v11.39.0), or highlighted changes and tips in the weekly [Shifty Bits newsletter](https://shiftybits.news).
- Checkout the `shift-ci-v11.39.0` branch
=> Laravel 11.39.0 Shift
